version: '3.9'

services:
  back:
    build:
      context: ./back
      target: ci
    depends_on:
      - test-database
    environment:
      - TEST_DATABASE_URL=postgres://postgres:root@test-database:5432/postgres

  test-database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    container_name: db_test_redlion
